project_name: assume-role
archive:
  format_overrides:
    - goos: darwin
      format: zip
  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    # Path to main.go file or main package.
    main: ./cli/assume-role/main.go
    # Binary name.
    # Can be a path (e.g. `bin/app`) to wrap the binary in a directory.
    # Default is the name of the project directory.
    binary: assume-role
    # GOOS list to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are darwin and linux.
    goos:
      - darwin
      - linux
    # GOARCH to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are 386 and amd64.
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/uber/assume-role-cli/cli.version={{.Version}} -X github.com/uber/assume-role-cli/cli.commit={{.ShortCommit}} -X github.com/uber/assume-role-cli/cli.date={{.Date}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
