name: release

on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Golang
        uses: actions/setup-go@master
        with:
          go-version: '1.13'
      - name: Do release
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
